apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang
spec:
  selector:
    matchLabels:
      app: golang
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: golang
        tier: backend
    spec:
      containers:
      - name: service
        image: ${DOCKER_REGISTRY:=jethro1412/golang_ci}:${VERSION:=1.0.0}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080