basePath: /swagger
consumes:
    - application/json
definitions:
    ApiRequests:
        properties:
            request:
                items:
                    format: int64
                    type: integer
                type: array
                x-go-name: Bar
            sample:
                type: string
                x-go-name: Foo
        type: object
        x-go-package: github.com/jethro1412/golang_ci/api
    ApiResponse:
        properties:
            baz:
                properties:
                    prop:
                        type: string
                        x-go-name: Prop
                type: object
                x-go-name: Baz
        type: object
        x-go-package: github.com/jethro1412/golang_ci/api
host: Localhost
info:
    description: Documentation of our swagger API.
    title: our golang swagger api for testing
    version: 1.0.0
paths:
    /api:
        post:
            operationId: idOfAPIEndpoint
            responses:
                "200":
                    $ref: '#/responses/ApiResponse'
            summary: This api does some amazing stuff.
            tags:
                - api
produces:
    - application/json
responses:
    ApiResponse:
        description: This text will appear as description of your response body.
        schema:
            $ref: '#/definitions/ApiResponse'
schemes:
    - http
securityDefinitions:
    basic:
        type: basic
swagger: "2.0"
